export const FETCH_M_HOTEL = "FETCH_M_HOTEL";
export const FETCH_M_HOTEL_LIST = "FETCH_M_HOTEL_LIST";
export const FETCH_M_ROOM_LIST = "FETCH_M_ROOM_LIST";
export const FETCH_M_ROOM = "FETCH_M_ROOM";
export const IS_LOGGEDIN = "IS_LOGGEDIN";
export const NOT_LOGGEDIN = "NOT_LOGGEDIN";
export const SET_USER = "SET_USER"; //얘 빼야 하는듯?
export const GET_HOTEL_TYPE = "GET_HOTEL_TYPE";
export const FETCH_BM_HOTEL = "FETCH_BM_HOTEL";
export const FETCH_BM_HOTEL_LIST = "FETCH_BM_HOTEL_LIST";
export const FETCH_BM_ROOM = "FETCH_BM_ROOM";
export const FETCH_BM_ROOM_LIST = "FETCH_BM_ROOM_LIST";
export const FETCH_WISH_LISTS = "FETCH_WISH_LISTS";
export const FETCH_BOOKING_LISTS = "FETCH_BOOKING_LISTS";
